# Generated by Django 5.1.5 on 2025-01-24 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imei', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Token',
            new_name='TokenTG',
        ),
    ]
